version: '3.7'

networks:
  slurm:

volumes:
  jhubstate:

configs:
  munge_key:
    file: ./munge/munge.key
  jupyterhub_config:
    file: ./jupyterhub/jupyterhub_config.py
  cull_idle_config:
    file: ./jupyterhub/cull_idle_servers.py

services:
  slurmctld:
    image: nielsbohr/slurmctld:edge
    hostname: slurmctld
    container_name: slurmctld
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - ./config/slurm.conf:/etc/slurm/slurm.conf:ro
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
    networks:
      - slurm
    command: sudo -u munge munged && sudo -u slurm slurmctld -D
  worker01:
    image: nielsbohr/slurmd:edge
    hostname: worker01
    container_name: worker01
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - ./config/slurm.conf:/etc/slurm/slurm.conf:ro
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
    networks:
      - slurm
  jupyterhub:
    image: nielsbohr/jupyterhub:latest
    hostname: jupyterhub
    container_name: jupyterhub
    environment:
      TZ: Europe/Copenhagen
    ports: 
      - "80:8000"
    configs:
      - source: jupyterhub_config
        target: /etc/jupyterhub/jupyterhub_config.py
        mode: 0440
      - source: cull_idle_config
        target: /srv/jupyterhub/cull_idle_servers.py
        mode: 0440
    networks:
      - slurm
    command: jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
    volumes:
      # The jupyterhub service needs accces to the docker daemon process
      # to launch addtional notebook services from within the service itself
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # Keep the jhub states such as the db saved during restarts
      - type: volume
        source: jhubstate
        target: /srv/jupyterhub
