version: '3.7'

volumes:
  jhubstate:

configs:
  munge_key:
    file: ./munge/munge.key
  slurm_conf:
    file: ./config/slurm.conf
  jupyterhub_config:
    file: ./jupyterhub/jupyterhub_config.py
  cull_idle_config:
    file: ./jupyterhub/cull_idle_servers.py

services:
  slurmctld:
    image: nielsbohr/slurmctld:edge
    hostname: slurmctld
    container_name: slurmctld
    environment:
      TZ: Europe/Copenhagen
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
    command: sudo -u munge munged && sudo -u slurm slurmctld -D
  openldap:
    image: osixia/openldap:1.2.3
    environment:
      TZ: Europe/Copenhagen
    
  jupyterhub:
    image: nielsbohr/jupyterhub:latest
    hostname: jupyterhub
    container_name: jupyterhub
    environment:
      TZ: Europe/Copenhagen
    ports: 
      - "80:8000"
    configs:
      - source: jupyterhub_config
        target: /etc/jupyterhub/jupyterhub_config.py
        mode: 0440
      - source: cull_idle_config
        target: /srv/jupyterhub/cull_idle_servers.py
        mode: 0440
    command: jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
    volumes:
      # The jupyterhub service needs accces to the docker daemon process
      # to launch addtional notebook services from within the service itself
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./notebook:/srv/jupyterhub/notebook:rw
      # Keep the jhub states such as the db saved during restarts
      - type: volume
        source: jhubstate
        target: /srv/jupyterhub
  worker01:
    image: nielsbohr/slurmd:edge
    hostname: worker01
    environment:
      TZ: Europe/Copenhagen
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
  worker02:
    image: nielsbohr/slurmd:edge
    hostname: worker02
    environment:
      TZ: Europe/Copenhagen
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
  worker03:
    image: nielsbohr/slurmd:edge
    hostname: worker03
    environment:
      TZ: Europe/Copenhagen
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
      - source: slurm_conf
        target: /etc/slurm/slurm.conf
