version: '3.7'

services:
  slurmctld:
    image: nielsbohr/slurmctld:edge
    hostname: slurmctld
    container_name: slurmctld
    volumes:
      - ./config/slurm.conf:/etc/slurm/slurm.conf:ro
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
    networks:
      - slurm
    command: sudo -u munge munged && sudo -u slurm slurmctld -D
  worker01:
    image: nielsbohr/slurmd:edge
    hostname: worker01
    container_name: worker01
    volumes:
      - ./config/slurm.conf:/etc/slurm/slurm.conf:ro
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
    networks:
      - slurm
  worker02:
    image: nielsbohr/slurmd:edge
    hostname: worker02
    container_name: worker02
    volumes:
      - ./config/slurm.conf:/etc/slurm/slurm.conf:ro
    configs:
      - source: munge_key
        target: /etc/munge/munge.key
        uid: '997'
        gid: '993'
        mode: 0400
    networks:
      - slurm

networks:
  slurm:

configs:
  munge_key:
    file: ./munge/munge.key